title: Digits
description: A quick guideline for starting the Digits application development
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
url: https://jang-taeyang.github.io/digits


gems:
  - jekyll-mentions
